/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Video = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'creator_name' : IDL.Text,
  'subject' : IDL.Text,
  'description' : IDL.Text,
  'is_published' : IDL.Bool,
  'thumbnail_url' : IDL.Text,
});
export const Textbook = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'price' : IDL.Text,
  'seller_name' : IDL.Text,
  'condition' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPublishedVideos' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Video))],
      ['query'],
    ),
  'getAllTextbooks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Textbook))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'insertTextbook' : IDL.Func([Textbook], [IDL.Nat], []),
  'insertVideo' : IDL.Func([Video], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Video = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'creator_name' : IDL.Text,
    'subject' : IDL.Text,
    'description' : IDL.Text,
    'is_published' : IDL.Bool,
    'thumbnail_url' : IDL.Text,
  });
  const Textbook = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'price' : IDL.Text,
    'seller_name' : IDL.Text,
    'condition' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPublishedVideos' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Video))],
        ['query'],
      ),
    'getAllTextbooks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Textbook))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'insertTextbook' : IDL.Func([Textbook], [IDL.Nat], []),
    'insertVideo' : IDL.Func([Video], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };